<?php $_order = $this->getOrder() ?>
<?php $_orderData = Mage::helper('moogento_shipeasy/sales')->getOrderM2EProData($_order); ?>
<?php if(isset($_orderData['id'])): ?>
<div class="box-left" id="m2epro_order_view">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $_orderData['target'].' data from M2ePro';?></h4>
        </div>
        <div class="fieldset-left">
            <div class="m2epro">
				<fieldset>
	                <span> Order:</span>
	                <table cellspacing="0" class="form-list order_data">
	                    <tbody>
	                        <?php foreach ($_orderData['data'] as $order_data):?>
	                        <tr>
	                            <td class='title'>
	                                <?php echo $order_data['title']; ?>
	                            </td>
	                            <td class='data'>
	                                <?php echo $order_data['data']; ?>
	                            </td>
	                        </tr>
	                        <?php endforeach; ?>
	                    </tbody>
	                </table>
	                <?php if(isset($_orderData['order_link'])): ?>
	                    <span> 
	                        <a href="<?php echo $_orderData['order_link']?>">See order @ <?php echo $_orderData['target'] ?></a> 
	                    </span>
	                    <br/><br/>
	                <?php endif; ?>
	                <span> Product<?php if( (count($_orderData['products']))>1 ) echo 's'; ?> ordered @ <?php echo $_orderData['target'] ?>:</span>
	                <table cellspacing="0" class="form-list products_data">
	                    <tbody>
	                        <?php foreach ($_orderData['products'] as $products):?>
	                        <tr>
	                            <td class='product_name'>
	                                <?php echo $products['name']; ?>
	                            </td>
	                            <td class='magento_link'>
	                                <a href="<?php echo $products['magento_link'] ?>"> See product @ frontend store</a>
	                            </td>
	                            <td class='merchant_link'>
	                                <a href="<?php echo $products['merchant_link'] ?>"> See product @ <?php echo $_orderData['target'] ?></a>
	                            </td>
	                        </tr>
	                        <?php endforeach; ?>
	                    </tbody>
	                </table>
				</fieldset>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<?php endif; ?>