<?php
    $element = $this->getElement();
    $htmlId = $element->getHtmlId();

    if ($element->getExpanded() !== null) {
        $collapseState = 1;
    } else {
        $extra = Mage::getSingleton('admin/session')->getUser()->getExtra();
        if (isset($extra['configState'][$element->getId()])) {
            $collapseState = (int)$extra['configState'][$element->getId()];
        } else {
            $collapseState = 0;
        }
    }

?>
<div class="section-config" xmlns="http://www.w3.org/1999/html">
    <div class="entry-edit-head collapseable">
        <a onclick="Fieldset.toggleCollapse('<?php echo $htmlId ?>', '<?php echo $this->getUrl('*/*/state/')?>'); return false;" href="#" id="<?php echo $htmlId ?>-head" class="">
            <?php echo $element->getLegend() ?>
        </a>
    </div>
    <input type="hidden" value="<?php echo $collapseState ?>" name="config_state[<?php echo $htmlId ?>]" id="<?php echo $htmlId ?>-state">
    <fieldset id="<?php echo $htmlId ?>" class="config collapseable grid">
        <table class="data" cellspacing="0">
            <thead>
            <tr class="headings">
                <th style="width: 125px;">&nbsp;</th>
                <th style="width: 200px;"><?php echo $this->__('Product attribute') ?></th>
                <th style="width: 200px;"><?php echo $this->__('Grid column title') ?></th>
                <th style="width: 100px;"><?php echo $this->__('Width') ?></th>
                <th><?php echo $this->__('Attribute-specific settings') ?></th>
            </tr>
            </thead>
            <tbody class="toggle-light" data-bind="sortable: {data: columns, afterMove: updateOrder}">
                <tr>
                    <td>
                        <span class="icon-drag"></span>
                        <span style="display: inline-block">
                            <input type="hidden" value="0" data-bind="attr: {name: buildName('show')}" />
                            <input type="checkbox" value="1" data-bind="attr: {name: buildName('show')}, checked: show, switch: show" />
                        </span>
                        <input style="width: 40px" type="text" class="input-text" data-bind="value: order, attr: {name: buildName('order')}" />
                    </td>
                    <td data-bind="text:orig_header"></td>
                    <td>
                        <input type="text" class="input-text" data-bind="value: header, attr: {name: buildName('header')}" />
                    </td>
                    <td style="width: 100px;">
                        <input type="text" class="input-text input-width" data-bind="value: width, attr: {name: buildName('width')}" />
                    </td>
                    <td>
                        <div data-bind="visible: show">
                            <!-- ko foreach:additionalFields -->
                            <div data-bind="template: {name: $data.tpl, data: $data}, visible: index() < 3 || $parent.showAll">

                            </div>
                            <!-- /ko -->
                            <a data-bind="click: doShowAll, visible: visibleFields().length > 3 && !showAll()">Show all</a>
                            <div class="clearfix"></div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
	    <h5>
		    <?php echo $this->__('Add more product attributes to grid') ?>
	    </h5>
	    <select multiple="multiple" data-bind="chosen: {width: '400px'}, selectedOptions: gridAttributes" name="groups[grid][fields][attributes][value][]">
		    <?php foreach ($this->_getAttributes() as $attribute): ?>
			    <option value="<?php echo $attribute['value'] ?>"><?php echo $attribute['label'] ?></option>
		    <?php endforeach; ?>
	    </select>

        <h5>
            <?php echo $this->__('Color product lines based on EDX') ?>&nbsp; &nbsp;
            <button style="margin-bottom: -6px;margin-top: 6px;" class="add" data-bind="click: addColor"><span><?php echo $this->__('Add New : EDX/Color Match') ?></span></button>
        </h5>
		<span style="font-weight: 100;margin:-17px 0 4px;display: block;font-style: italic;color: #555;"><?php echo $this->__('EDX = Estimated Days until out-of-stock'); ?></span>
        <table class="data" cellspacing="0" style="width: 400px;">
            <thead>
                <tr class="headings">
                    <th style="width: 200px;"><?php echo $this->__('EDX') ?></th>
                    <th style="width: 200px;"><?php echo $this->__('Color') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody class="toggle-light" data-bind="foreach: cellColors">
                <tr>
                    <td>
                        <input type="text" class="" data-bind="value: days, attr: {name: $parent.buildColorName('days', $data.id)}" />
                    </td>
                    <td>
                        <input type="text" class="" data-bind="value: color, color: color, attr: {name: $parent.buildColorName('color', $data.id)}" />
                    </td>
                    <td>
	                    <a href="#" class="fa fa-times" style="color: red" data-bind="click: $parent.removeColor"></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <div style="display: none">
        <div id="field-template-checkbox">
            <div class="additional-field" data-bind="visible: isVisible">
                <label data-bind="visible: !hideLabel()">
                    <span data-bind="html: label"></span>
                        <span data-bind="visible: comment()" class="helper-info">
                            <i>?</i>
                            <div class="content" data-bind="html: comment"></div>
                        </span>
                </label>
                <input type="hidden" value="0" data-bind="attr: {name: $parents[1].buildName($data.key())}" />
                <input type="checkbox" value="1" data-bind="attr: {name: $parents[1].buildName($data.key())}, checked: checked, switch: checked" />
            </div>
        </div>
        <div id="field-template-text">
            <div class="additional-field" data-bind="visible: isVisible">
                <label data-bind="visible: !hideLabel()">
                    <span data-bind="html: label"></span>
                        <span data-bind="visible: comment()" class="helper-info">
                            <i>?</i>
                            <div class="content" data-bind="html: comment"></div>
                        </span>
                </label>
                <input type="text" class="input-text" data-bind="value: value, attr: {name: $parents[1].buildName($data.key())}" />
            </div>
        </div>
        <div id="field-template-select">
            <div class="additional-field" data-bind="visible: isVisible">
                <label data-bind="visible: !hideLabel()">
                    <span data-bind="html: label"></span>
                        <span data-bind="visible: comment()" class="helper-info">
                            <i>?</i>
                            <div class="content" data-bind="html: comment"></div>
                        </span>
                </label>
                <select class="chosen" data-bind="chosen: {width: '200px'}, value: value, attr: {name: $parents[1].buildName($data.key())}, options: options, optionsText: 'label', optionsValue: 'value'">
                </select>
            </div>
        </div>
        <div id="field-template-image">
            <div class="additional-field" data-bind="visible: isVisible">
                <div class="additional-field" data-bind="visible: isVisible">
                    <label data-bind="visible: !hideLabel()">
                        <span data-bind="html: label"></span>
                        <span data-bind="visible: comment()" class="helper-info">
                            <i>?</i>
                            <div class="content" data-bind="html: comment"></div>
                        </span>
                    </label>
                    <div data-bind="if: value">
                        <a data-bind="attr: {href: value}" target="_blank">
                            <img style="height:40px" data-bind="attr: {src: value}" />
                        </a>
                        <input type="checkbox" class="checkbox" value="1" data-bind="attr: {name: $parents[1].buildName($data.key()) + '[delete]'}"">
                        <?php echo $this->__('Delete image') ?>
                    </div>
                    <input type="file" class="input-file" data-bind="attr: {name: $parents[1].buildName($data.key())}" />
                </div>
            </div>
        </div>
        <div id="field-template-textarea">
            <div class="additional-field" data-bind="visible: isVisible">
                <label data-bind="visible: !hideLabel()">
                    <span data-bind="html: label"></span>
                    <span data-bind="visible: comment()" class="helper-info">
                        <i>?</i>
                        <div class="content" data-bind="html: comment"></div>
                    </span>
                </label>
                <textarea rows="3" cols="30" data-bind="value: value, attr: {name: $parents[1].buildName($data.key())}"></textarea>
            </div>
        </div>
        <div id="field-template-multiselect" data-bind="visible: isVisible">
            <div class="additional-field">
                <label data-bind="visible: !hideLabel()">
                    <span data-bind="html: label"></span>
                    <span data-bind="visible: comment()" class="helper-info">
                        <i>?</i>
                        <div class="content" data-bind="html: comment"></div>
                    </span>
                </label>
                <select class="chosen" multiple="true" data-bind="chosen: {width: '200px'}, selectedOptions: value, attr: {name: $parents[1].buildName($data.key(), true)}, options: options, optionsText: 'label', optionsValue: 'value'">
                </select>
            </div>
        </div>
        <div id="field-template-serializable_table">
            <table class="data" cellspacing="0" style="width: 450px">
                <thead>
                    <tr class="headings">
                        <!-- ko foreach: fields -->
                        <th data-bind="text: $data.label"></th>
                        <!-- /ko -->
                        <th></th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: rows">
                    <tr>
                        <!-- ko foreach: fields -->
                        <td data-bind="template:{name: $data.tpl, data: $data}">

                        </td>
                        <!-- /ko -->
                        <td>
                            <button data-bind="click: $parents[1].removeRow" type="button" class="scalable delete delete-select-row icon-btn"><span></span></button>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td class="a-right" colspan="3">
                            <button class="scalable add add-select-row" type="button" data-bind="click: addRow"><span><?php echo $this->__('Add') ?></span></button>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <script type="text/javascript">
        Fieldset.applyCollapse('<?php echo $htmlId ?>');
        ko.applyBindings(new GridColumns(
	        <?php echo $this->_getColumnsJson() ?>,
		        {
			        colors: <?php echo Mage::getStoreConfig('moogento_stockeasy/grid/cell_colors') ?>,
			        gridAttributes: '<?php echo Mage::getStoreConfig('moogento_stockeasy/grid/attributes') ?>'
		        }),
	        document.getElementById('<?php echo $htmlId ?>'));
    </script>
    <style>
        .additional-field {
            float: left;
            margin-right: 15px;
        }
        .helper-info i {
            font-size: 10px;
            font-weight: bold;
            line-height: 12px;
            text-align: center;
            position: absolute;
            left: 3px;
            font-style: normal;
        }
        .helper-info {
            background: none repeat scroll 0 0 lightgrey;
            border: 1px solid lightgrey;
            border-radius: 6px;
            display: inline-block;
            height: 12px;
            position: relative;
            width: 12px;
        }
        .helper-info div.content {
            display: none;
            position: absolute;
            width: 400px;
            border: 1px solid black;
            background: lightgrey;
            box-shadow: 1px 1px #000;
        }
        .helper-info:hover div.content {
            display: block;
            z-index: 1000;
            top:12px;
        }
    </style>
</div>