<?php
$element = $this->getElement();
$htmlId = $element->getHtmlId();

if ($element->getExpanded() !== null) {
    $collapseState = 1;
} else {
    $extra = Mage::getSingleton('admin/session')->getUser()->getExtra();
    if (isset($extra['configState'][$element->getId()])) {
        $collapseState = (int)$extra['configState'][$element->getId()];
    } else {
        $collapseState = 0;
    }
}

?>
<div class="section-config">
<div class="entry-edit-head collapseable">
    <a onclick="Fieldset.toggleCollapse('<?php echo $htmlId ?>', '<?php echo $this->getUrl('*/*/state/')?>'); return false;" href="#" id="<?php echo $htmlId ?>-head" class="">
        <?php echo $element->getLegend() ?>
    </a>
</div>
<input type="hidden" value="<?php echo $collapseState ?>" name="config_state[<?php echo $htmlId ?>]" id="<?php echo $htmlId ?>-state">
<fieldset id="<?php echo $htmlId ?>" class="config collapseable grid">
    <table class="data" cellspacing="0">
        <thead>
        <tr class="headings">
            <th style="width: 51px;">&nbsp;</th>
            <th>
                <?php echo $this->__('Target email &amp; template') ?>
            </th>
            <th>
                <?php echo $this->__('Report Type') ?>
            </th>
            <th>
                <?php echo $this->__('Only with Attribute (1)') ?>
            </th>
            <th>
                <?php echo $this->__('Only with Attribute (2)') ?>
            </th>
            <th>
                <?php echo $this->__('Only if Qty &lt; Trigger Qty') ?>
            </th>
            <th>
                <?php echo $this->__('Only if Reorder Qty > 0') ?>
            </th>
            <th>
                <?php echo $this->__('Only if Status = Enabled') ?>
            </th>
            <th>
                <?php echo $this->__('Auto-email: days').'<br /><span style="font-weight: 100;margin-top: -11px;display: block;font-style: italic;color: #fff;">'.$this->__('Email on which days?').'</span>'; ?>
            </th>
            <th>
               <?php echo $this->__('Auto-email: time').'<br /><span style="font-weight: 100;margin-top: -11px;display: block;font-style: italic;color: #fff;">'.$this->__('Email at what time?').'</span>'; ?>
            </th>
        </tr>
        </thead>
        <tbody class="toggle-light" data-bind="foreach: configs">
        <tr>
            <td class="moo_rule_toggle">
	            <span data-bind="click: $parent.deleteConfig" class="fa fa-times" style="color: red; cursor: pointer"></span>
                <span class="moo_onoff_toggle">
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('enable')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('enable')}, checked: enable, switch: enable" />
                </span>
            </td>
            <td>
                <input type="text" data-bind="value: email, attr: {name: buildName('email')}" />
                <select class="chosen" data-bind="value: template_type, attr: {name: buildName('template_type')}">
                    <option value=""></option>
                    <?php foreach (Mage::helper('moogento_stockeasy')->getEmailTemplatesOptions() as $_option): ?>
                    <option value="<?php echo $_option['value'] ?>"><?php echo $_option['label'] ?></option>
                    <?php endforeach; ?>
                </select>
                <br/>
                <br/><button class="button" data-bind="click: test($index)" title="<?php echo $this->__('Please save changes before testing') ?>"><span><?php echo $this->__('Test') ?></span></button>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: stock_type, attr: {name: buildName('stock_type')}">
                    <option value="in_stock">In Stock</option>
                    <option value="low_stock">Low Stock</option>
                    <option value="inventory_change">Inventory Change</option>
                </select>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: type, attr: {name: buildName('type')}">
                    <option value="csv">CSV</option>
                    <option value="pdf">PDF</option>
                </select>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '140px', allow_single_deselect: true}, value: filterByAttribute, attr: {name: buildName('filter_attribute')}, options: $root.attributes, optionsValue: 'code', optionsText: 'label'">
                </select>
                <div data-bind="if: selectedAttribute()">
                    <div data-bind="template: {name: selectedAttribute().template(), data: selectedAttribute()} "></div>
                </div>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '140px', allow_single_deselect: true}, value: filterBySecondAttribute, attr: {name: buildName('filter_second_attribute')}, options: $root.attributes, optionsValue: 'code', optionsText: 'label'">
                </select>
                <div data-bind="if: selectedSecondAttribute()">
                    <div data-bind="template: {name: selectedSecondAttribute().template() + '_second', data: selectedSecondAttribute()} "></div>
                </div>
            </td>
            <td>
                <span style="display: inline-block">
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('filter_trigger_qty')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('filter_trigger_qty')}, checked: filterTriggerQty, switch: filterTriggerQty" />
                </span>
            </td>
            <td>
                <span style="display: inline-block">
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('filter_reorder_qty')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('filter_reorder_qty')}, checked: filterReorderQty, switch: filterReorderQty" />
                </span>
            </td>
            <td>
                <span style="display: inline-block">
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('filter_enabled')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('filter_enabled')}, checked: filterEnabled, switch: filterEnabled" />
                </span>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '140px'}, value: sendType, attr: {name: buildName('send_type')}">
                    <option value="mon_fri"><?php echo $this->__('Mon-Fri') ?></option>
                    <option value="days"><?php echo $this->__('Week days') ?></option>
                    <option value="end_month"><?php echo $this->__('End of month') ?></option>
                </select>
                <div data-bind="visible: sendType() == 'days'">
                    <select class="chosen" multiple="multiple" data-bind="chosen: {width: '140px'}, selectedOptions: sendDays, attr: {name: buildName('send_days', '')}">
                        <?php $source = Mage::getModel('adminhtml/system_config_source_locale_weekdays') ?>
                        <?php foreach ($source->toOptionArray() as $option): ?>
                            <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: sendTime, attr: {name: buildName('send_time')}">
                    <?php for ($i = 0; $i < 24; $i++): ?>
                        <option value="<?php echo $i ?>"><?php echo str_pad($i, 2, '0', STR_PAD_LEFT) ?>:00</option>
                    <?php endfor; ?>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <h5>
        <button class="add" data-bind="click: addConfig"><span><?php echo $this->__('Add New : Auto-Email') ?></span></button>
    </h5>
</fieldset>

<div style="display: none">
    <div id="template-attribute-boolean">
        <input type="hidden" value="0" data-bind="attr: {name: $parent.buildName('filter_value')}" />
	    <input type="checkbox" value="1" data-bind="attr: {name: $parent.buildName('filter_value')}, checked: $parent.filterByAttributeValue, switch: $parent.filterByAttributeValue" />
    </div>
    <div id="template-attribute-text">
        <input type="text" class="input-text" data-bind="value: $parent.filterByAttributeValue, attr: {name: $parent.buildName('filter_value')}" />
    </div>
    <div id="template-attribute-multiselect">
        <select class="chosen" multiple="true" data-bind="chosen: {width: '140px'}, selectedOptions: $parent.filterByAttributeValueArray, attr: {name: $parent.buildName('filter_value', '')}, options: options, optionsText: 'label', optionsValue: 'value'">
        </select>
    </div>
	<div id="template-attribute-range">
		<?php echo $this->__('From') ?>: <input type="text" style="width: 70%" class="input-text" data-bind="value: $parent.filterByAttributeValueRange().from(), attr: {name: $parent.buildName('filter_value', 'from')}" /><br/>
		<?php echo $this->__('To') ?>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%" class="input-text" data-bind="value: $parent.filterByAttributeValueRange().to(), attr: {name: $parent.buildName('filter_value', 'to')}" />
	</div>
	<div id="template-attribute-date">
		<?php echo $this->__('From') ?>: <input type="text" style="width: 70%" class="input-text" data-bind="datepicker: {value: $parent.filterByAttributeValueRange().from, dateFormat: 'yy-mm-dd'}, attr: {name: $parent.buildName('filter_value', 'from')}" /><br/>
		<?php echo $this->__('To') ?>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%" class="input-text" data-bind="datepicker: {value: $parent.filterByAttributeValueRange().to(), dateFormat: 'yy-mm-dd'}, attr: {name: $parent.buildName('filter_value', 'to')}" />
	</div>

    <div id="template-attribute-boolean_second">
        <input type="hidden" value="0" data-bind="attr: {name: $parent.buildName('filter_second_value')}" />
        <input type="checkbox" value="1" data-bind="attr: {name: $parent.buildName('filter_second_value')}, checked: $parent.filterBySecondAttributeValue, switch: $parent.filterBySecondAttributeValue" />
    </div>
    <div id="template-attribute-text_second">
        <input type="text" class="input-text" data-bind="value: $parent.filterBySecondAttributeValue, attr: {name: $parent.buildName('filter_second_value')}" />
    </div>
    <div id="template-attribute-multiselect_second">
        <select class="chosen" multiple="true" data-bind="chosen: {width: '140px'}, selectedOptions: $parent.filterBySecondAttributeValueArray, attr: {name: $parent.buildName('filter_second_value', '')}, options: options, optionsText: 'label', optionsValue: 'value'">
        </select>
    </div>
    <div id="template-attribute-range_second">
        <?php echo $this->__('From') ?>: <input type="text" style="width: 70%" class="input-text" data-bind="value: $parent.filterBySecondAttributeValueRange().from(), attr: {name: $parent.buildName('filter_second_value', 'from')}" /><br/>
        <?php echo $this->__('To') ?>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%" class="input-text" data-bind="value: $parent.filterBySecondAttributeValueRange().to(), attr: {name: $parent.buildName('filter_second_value', 'to')}" />
    </div>
    <div id="template-attribute-date_second">
        <?php echo $this->__('From') ?>: <input type="text" style="width: 70%" class="input-text" data-bind="datepicker: {value: $parent.filterBySecondAttributeValueRange().from, dateFormat: 'yy-mm-dd'}, attr: {name: $parent.buildName('filter_second_value', 'from')}" /><br/>
        <?php echo $this->__('To') ?>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="width: 70%" class="input-text" data-bind="datepicker: {value: $parent.filterBySecondAttributeValueRange().to(), dateFormat: 'yy-mm-dd'}, attr: {name: $parent.buildName('filter_second_value', 'to')}" />
    </div>
</div>
<script type="text/javascript">
    var TEST_EMAIL_URL = '<?php echo $this->getUrl('*/stockeasy_config/testEmail') ?>';
    Fieldset.applyCollapse('<?php echo $htmlId ?>');
    ko.applyBindings(new CronConfigModule.CronConfigs(<?php echo $this->_getJson() ?>, <?php echo $this->_getAttributes() ?>), document.getElementById('<?php echo $htmlId ?>'));
</script>
</div>