<?php
$element = $this->getElement();
$htmlId = $element->getHtmlId();

if ($element->getExpanded() !== null) {
    $collapseState = 1;
} else {
    $extra = Mage::getSingleton('admin/session')->getUser()->getExtra();
    if (isset($extra['configState'][$element->getId()])) {
        $collapseState = (int)$extra['configState'][$element->getId()];
    } else {
        $collapseState = 0;
    }
}

?>
<div class="section-config">
<div class="entry-edit-head collapseable">
    <a onclick="Fieldset.toggleCollapse('<?php echo $htmlId ?>', '<?php echo $this->getUrl('*/*/state/')?>'); return false;" href="#" id="<?php echo $htmlId ?>-head" class="">
        <?php echo $element->getLegend() ?>
    </a>
</div>
<input type="hidden" value="<?php echo $collapseState ?>" name="config_state[<?php echo $htmlId ?>]" id="<?php echo $htmlId ?>-state">
<fieldset id="<?php echo $htmlId ?>" class="config collapseable grid">
    <table class="data" cellspacing="0">
        <thead>
        <tr class="headings">
            <th style="width: 51px;">&nbsp;</th>
            <th>
                <?php echo $this->__('Email for error reports') ?>
            </th>
            <th>
                <?php echo $this->__('Import type') ?>
            </th>
            <th>
                <?php echo $this->__('Import method') ?>
            </th>
            <th>
                <?php echo $this->__('Product attribute mapping').'<br /><span style="font-weight: 100;margin-top: -11px;display: block;font-style: italic;color: #fff;">'.$this->__('CSV fields or XML tags').'</span>'; ?>
            </th>
            <th>
                <?php echo $this->__('Auto-import: days').'<br /><span style="font-weight: 100;margin-top: -11px;display: block;font-style: italic;color: #fff;">'.$this->__('Import on which days?').'</span>'; ?>
            </th>
            <th>
                <?php echo $this->__('Auto-import: time').'<br /><span style="font-weight: 100;margin-top: -11px;display: block;font-style: italic;color: #fff;">'.$this->__('Import at what time?').'</span>'; ?>
            </th>
        </tr>
        </thead>
        <tbody class="toggle-light" data-bind="foreach: configs">
        <tr>
            <td class="moo_rule_toggle">
                <span data-bind="click: $parent.deleteConfig" class="fa fa-times" style="color: red; cursor: pointer"></span>
                <span class="moo_onoff_toggle">
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('enable')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('enable')}, checked: enable, switch: enable" />
                </span>
            </td>
            <td>
                <input style="width: 152px;" type="text" data-bind="value: errors_email, attr: {name: buildName('errors_email')}" />
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: file_type, attr: {name: buildName('file_type')}">
                    <option value="csv">CSV</option>
                    <option value="xml">XML</option>
                </select>
                <div data-bind="visible: file_type() == 'csv'">
                    <label><?php echo $this->__("CSV column delimiter"); ?></label>
                    <input type="text" data-bind="value: column_delimiter, attr: {name: buildName('column_delimiter')}" />
                </div>
                <div data-bind="visible: file_type() == 'xml'">
                    <label><?php echo $this->__("Product root element"); ?></label>
                    <input type="text" data-bind="value: xml_element, attr: {name: buildName('xml_element')}" />
                </div>
                <div>
                    <?php echo $this->__('Force store id?') ?><br/>
                    <span>
                        <input type="hidden" value="0" data-bind="attr: {name: buildName('force_store')}" />
                        <input type="checkbox" value="1" data-bind="attr: {name: buildName('force_store')}, checked: force_store, switch: force_store" />
                    </span><br/>
                    <div data-bind="visible: force_store">
                        <?php echo $this->__('Store IDs (comma separated)') ?><br/>
                        <input type="text" data-bind="visible: force_store(), value: force_store_ids, attr: {name: buildName('force_store_ids')}" />
                    </div>
                </div>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: import_type, attr: {name: buildName('import_type')}">
                    <option value="url">URL</option>
                    <option value="file">File</option>
                    <option value="ftp">FTP</option>
                </select>
                <div data-bind="visible: import_type() == 'url'">
                    <label><?php echo $this->__("Full URL to file:"); ?></label>
                    <input type="text" data-bind="value: url_data, attr: {name: buildName('url_data')}" />
                </div>
                <div data-bind="visible: import_type() == 'file'">
                    <label><?php echo $this->__("Path to file:"); ?></label>
                    <input type="text" data-bind="value: file_data, attr: {name: buildName('file_data')}" />
                </div>
                <div data-bind="visible: import_type() == 'ftp'">
                    <div>
                        <label><?php echo $this->__("FTP host"); ?></label>
                        <input type="text" data-bind="value: ftp_host, attr: {name: buildName('ftp_host')}" />
                    </div>
                    <div>
                        <label><?php echo $this->__("FTP port"); ?></label>
                        <input type="text" data-bind="value: ftp_port, attr: {name: buildName('ftp_port')}" />
                    </div>
                    <div>
                        <label><?php echo $this->__("FTP username"); ?></label>
                        <input type="text" data-bind="value: ftp_username, attr: {name: buildName('ftp_username')}" />
                    </div>
                    <div>
                        <label><?php echo $this->__("FTP password"); ?></label>
                        <input type="text" data-bind="value: ftp_pass, attr: {name: buildName('ftp_pass')}" />
                    </div>
                    <div>
                        <label><?php echo $this->__("FTP path"); ?></label>
                        <input type="text" data-bind="value: ftp_path, attr: {name: buildName('ftp_path')}" />
                    </div>
                    <div>
                        <label><?php echo $this->__("FTP file"); ?></label>
                        <input type="text" data-bind="value: ftp_file, attr: {name: buildName('ftp_file')}" />
                    </div>
                </div>
                <br/><button class="button" data-bind="click: test($index)" title="<?php echo $this->__('Please save changes before testing') ?>"><span><?php echo $this->__('Test') ?></span></button>
            </td>
            <td>
                <div id="import_options_import_columns">
                    <div class="leftcol">
                        <div>
                            <label><?php echo $this->__("Sku"); ?></label>
                            <input type="text" data-bind="value: sku_column, attr: {name: buildName('sku_column')}" />
                        </div>
                        <div>
                            <label><?php echo $this->__("ID"); ?></label>
                            <input type="text" data-bind="value: id_column, attr: {name: buildName('id_column')}" />
                        </div>
                        <div>
                            <label>
                                <?php echo $this->__("Store ID"); ?>
                            </label>
                            <input type="text" data-bind="value: store_id_column, attr: {name: buildName('store_id_column')}" />
                        </div>
                        <div>
                            <label><?php echo $this->__("Qty"); ?></label>
                            <input type="text" data-bind="value: qty_column, attr: {name: buildName('qty_column')}" />
                        </div>
                    </div>
                    <div class="rightcol">
                        <div>
                            <label><?php echo $this->__("Price"); ?></label>
                            <input type="text" data-bind="value: price_column, attr: {name: buildName('price_column')}" />
                        </div>
                        <div>
                            <label><?php echo $this->__("Cost"); ?></label>
                            <input type="text" data-bind="value: cost_column, attr: {name: buildName('cost_column')}" />
                        </div>
                        <div>
                            <label><?php echo $this->__("Custom attribute"); ?></label>
                            <select class="chosen" data-bind="chosen: {width: '200px', allow_single_deselect: true}, value: additional_attribute, attr: {name: buildName('additional_attribute')}">
                                <?php $source = Mage::getModel('moogento_stockeasy/adminhtml_system_config_source_import_attributes') ?>
                                <?php foreach ($source->toOptionArray() as $option): ?>
                                    <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div>
                            <label><?php echo $this->__("Custom attribute field"); ?></label>
                            <input type="text" data-bind="value: additional_attribute_column, attr: {name: buildName('additional_attribute_column')}" />
                        </div>
                    </div>
                </div>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '140px'}, value: send_type, attr: {name: buildName('send_type')}">
                    <option value="days"><?php echo $this->__('Week days') ?></option>
                    <option value="end_month"><?php echo $this->__('End of month') ?></option>
                </select>
                <div data-bind="visible: send_type() == 'days'">
                    <select class="chosen" multiple="multiple" data-bind="chosen: {width: '140px'}, selectedOptions: send_days, attr: {name: buildName('send_days', '')}">
                        <?php $source = Mage::getModel('adminhtml/system_config_source_locale_weekdays') ?>
                        <?php foreach ($source->toOptionArray() as $option): ?>
                            <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </td>
            <td>
                <select class="chosen" data-bind="chosen: {width: '100px'}, value: send_time, attr: {name: buildName('send_time')}">
                    <?php for ($i = 0; $i < 24; $i++): ?>
                        <option value="<?php echo $i ?>"><?php echo str_pad($i, 2, '0', STR_PAD_LEFT) ?>:00</option>
                    <?php endfor; ?>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <h5>
        <button class="add" data-bind="click: addConfig"><span><?php echo $this->__('Add New : Auto-Import') ?></span></button>
    </h5>
</fieldset>

<script type="text/javascript">
    var TEST_CONNECTION_URL = '<?php echo $this->getUrl('*/stockeasy_config/testConnection') ?>';
    Fieldset.applyCollapse('<?php echo $htmlId ?>');
    ko.applyBindings(new ImportConfigModule.ImportConfigs(<?php echo $this->_getJson() ?>, <?php echo $this->_getAttributes() ?>), document.getElementById('<?php echo $htmlId ?>'));
</script>
</div>